/**

대여 기록 ID, 대여 금액
[조건] 자동차 종류 = 트럭 -> 8, 12, 20, 6
[조건] 대여금액 AS FEE
[정렬] 대여금액 기준 DESC, 대여기록ID 기준 DESC

1. 자동차 종류가 트럭인 데이터만 구함 + DATEDIFF로 변환해주기 -> FROM 서브쿼리
2. IF 통해서 요금 계산

DISCOUNT_RATE도 바뀔 수 있는데, 이걸 고려안함

**/

SELECT DISTINCT HISTORY_ID, FLOOR(DAILY_FEE * DATE_RANGE * CALCULATE / 100) AS FEE
FROM (
    SELECT CRCD.HISTORY_ID,
            CRCD.CAR_ID,
            CRCC.DAILY_FEE,
            DATEDIFF(CRCD.END_DATE, CRCD.START_DATE) + 1 AS DATE_RANGE,
            100 - 
            CASE
                WHEN DATEDIFF(CRCD.END_DATE, CRCD.START_DATE) + 1 >= 90
                THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '90일 이상' AND CAR_TYPE = '트럭')
                WHEN DATEDIFF(CRCD.END_DATE, CRCD.START_DATE) + 1 >= 30
                THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE = '트럭')
                WHEN DATEDIFF(CRCD.END_DATE, CRCD.START_DATE) + 1 >= 7
                THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '7일 이상' AND CAR_TYPE = '트럭')
                ELSE 0
            END AS CALCULATE
    FROM CAR_RENTAL_COMPANY_CAR AS CRCC
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCD
        ON CRCC.CAR_ID = CRCD.CAR_ID
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP
        ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE
    WHERE CRCC.CAR_TYPE = '트럭'
) AS A
ORDER BY FEE DESC, HISTORY_ID DESC
