/**

각 시간대별로 입양이 몇 건 발생했는지
[조건] 0시부터 23시까지
[정렬] 시간대 기준 ASC

데이터에 존재하지 않는 것들을 0으로 표기해야함
**/

SELECT HOUR, SUM(COUNT)
FROM (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS `COUNT`
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
    UNION SELECT 0, 0
    UNION SELECT 1, 0
    UNION SELECT 2, 0
    UNION SELECT 3, 0
    UNION SELECT 4, 0
    UNION SELECT 5, 0
    UNION SELECT 6, 0
    UNION SELECT 7, 0
    UNION SELECT 8, 0
    UNION SELECT 9, 0
    UNION SELECT 10, 0
    UNION SELECT 11, 0
    UNION SELECT 12, 0
    UNION SELECT 13, 0
    UNION SELECT 14, 0
    UNION SELECT 15, 0
    UNION SELECT 16, 0
    UNION SELECT 17, 0
    UNION SELECT 18, 0
    UNION SELECT 19, 0
    UNION SELECT 20, 0
    UNION SELECT 21, 0
    UNION SELECT 22, 0
    UNION SELECT 23, 0
) AS A
GROUP BY HOUR
ORDER BY HOUR ASC
