/**

년, 월, 성별 별로 상품을 구매한 회원수
[조건] 성별 정보가 없으면 제외
[정렬] 년, 월, 성별 기준으로 ASC

SELECT YEAR, MONTH, GENDER, COUNT(USER_ID)
GROUP BY YEAR, MONTH, GENDER

1) 서브쿼리로 YEAR, MONTH, GENDER, USER_ID를 가져온다. 여기서 성별 정보 없는건 WHERE절로 제외, 중복도 제거
2) GROUP BY 설정
3) SELECT 잘 만들기

**/

SELECT YEAR, MONTH, GENDER , COUNT(USER_ID) AS USERS
FROM (
    SELECT DISTINCT
        YEAR(OS.SALES_DATE) AS YEAR,
        MONTH(OS.SALES_DATE) AS MONTH,
        UI.GENDER,
        UI.USER_ID
    FROM USER_INFO AS UI
        JOIN ONLINE_SALE AS OS
        ON UI.USER_ID = OS.USER_ID
    WHERE UI.GENDER IS NOT NULL
) AS USER_INFO_ONLINE_SALE
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC
