/**

게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일 조회
[조건] 2022년 10월에 작성
[정렬] 댓글 작성일 기준 ASC, 게시글 제목 기준 ASC

- 2022년 10월에 작성된 게시글 기준인듯 (댓글로 하면 틀림)
**/

SELECT UGB.TITLE, UGB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, 
DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS UGB JOIN USED_GOODS_REPLY AS UGR ON UGB.BOARD_ID = 
UGR.BOARD_ID
WHERE UGB.CREATED_DATE >= '2022-10-01' AND UGB.CREATED_DATE < '2022-11-01'
ORDER BY UGR.CREATED_DATE ASC, UGB.TITLE ASC
