/**

도서 ID, 출판일 SQL
[조건] 2021년에 출판, 인문 카테고리
[정렬] 출판일 기준 ASC

**/


SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE PUBLISHED_DATE >= '2021-01-01' AND PUBLISHED_DATE < '2022-01-01' AND 
CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC
