/**

저자 ID, 저자명, 카테고리, 매출액 조회
[조건] 2022년 1월
[조건] 저자, 카테고리에 따라 나눔
[조건] 매출액 = 판매량 * 판매가
[정렬] 저자ID 기준 ASC, 카테고리 기준 DESC

**/

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM
    BOOK AS B
    JOIN AUTHOR AS A
    ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN BOOK_SALES AS BS
    ON B.BOOK_ID = BS.BOOK_ID
WHERE DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC
