/**

사람의 회원 ID, 닉네임, 총거래금액
[조건] 완료된 중고 거래의 총 금액이 70만원 이상인 사람
[정렬] 총거래금액 기준 ASC

**/

SELECT UGB.WRITER_ID, UGU.NICKNAME, SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS UGB JOIN USED_GOODS_USER AS UGU ON UGB.WRITER_ID = UGU.USER_ID
WHERE STATUS = 'DONE'
GROUP BY UGB.WRITER_ID
HAVING SUM(UGB.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC
