/**

식품들의 식품 ID, 식품 이름, 총매출을 조회
[조건] 생산일자가 2022년 5월
[정렬] 총매출 기준 DESC, 식품 ID 기준 ASC

PRODUCE_DATE = 생산일자

(FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FP.PRICE * FO.AMOUNT), FO.PRODUCE_DATE)
**/

SELECT PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM (
    SELECT 
        FP.PRODUCT_ID,
        FP.PRODUCT_NAME,
        FP.PRICE,
        FO.AMOUNT,
        DATE_FORMAT(FO.PRODUCE_DATE, '%Y-%m') AS DATETIME
    FROM
        FOOD_PRODUCT AS FP
        JOIN FOOD_ORDER AS FO
        ON FP.PRODUCT_ID = FO.PRODUCT_ID
) AS FOOD
WHERE DATETIME = '2022-05'
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
