/**

상품코드 별 매출액 합계를 출력
[조건] 매출액은 (판매가  판매량)의 합임
[정렬] 매출액 기준 DESC, 상품코드 기준 ASC

**/

SELECT P.PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT) AS SALES
FROM PRODUCT AS P JOIN OFFLINE_SALE AS O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC
