/**

상품과 상품 개수 출력하는 SQL문
[조건] 만원 단위의 가격대별로 나눈다
[조건] 컬럼명은 각각 PRICE_GROUP, PRODUCTS
[정렬] 가격대 기준 ASC

**/

SELECT PRICE_GROUP, COUNT(PRICE_GROUP)
FROM (SELECT (PRICE - PRICE % 10000) AS PRICE_GROUP FROM PRODUCT) AS PRODUCT_A
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP ASC
