/**

판매 날짜, 상품ID, 유저ID, 판매량
[조건] 2022년 3월 온라인/오프라인 상품 판매
[조건] OFFLINE_SALE의 USER_ID는 NULL로 표시
[정렬] 판매일 기준 ASC, 상품 ID 기준 ASC, 유저 ID ASC

**/
SELECT SALES_DATE, PRODUCT_ID, USER_ID AS USER_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
FROM 
    (SELECT PRODUCT_ID, USER_ID, SALES_AMOUNT, DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE
    FROM ONLINE_SALE
    UNION
    SELECT PRODUCT_ID, NULL, SALES_AMOUNT, DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE
    FROM OFFLINE_SALE) AS A
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
GROUP BY SALES_DATE, PRODUCT_ID, USER_ID
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC
